### ISSUE TITLE
Crypto trading

### ISSUE THREAD

**Issue by chengsu99** [mstrum/robinhood-python#24]
Hello mstrum. when I order crypto, it shows that "requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://nummus.robinhood.com/orders/". Do you find the same problem?

**Comment by mstrum** [comment]
Yep, that means it's not enabled for you yet. They are still rolling it out by state. I'm still waiting as well.

**Comment by chengsu99** [comment]
But I'm sure that I'm permitted to trade cryptocurrencies by using Robinhood APP.

**Comment by mstrum** [comment]
Oh, interesting, if that's the case you would need to debug it since I know I don't have access. If you find out anything let me know how it goes!

**Comment by chengsu99** [comment]
I'll try. Thank you for your code.

**Comment by aterletskiy** [comment]
Looks like crypto requests are authenticated definerrently.  I noticed there is a Bearer header in the requests from web app which I haven’t found a way to get yet, and Authorization header doesn’t work.

**Comment by aterletskiy** [comment]
You can migrate your regular token to oauth token by making a _POST_ request to this endpoint https://api.robinhood.com/oauth2/migrate_token/ .

**Comment by nickpdiana** [comment]
^This worked for me as well. Including my error message to help other people searching for this issue:
robinhood.exceptions.Forbidden: {'detail': 'Invalid Authorization header.'}

**Comment by Dalton2264** [comment]
> You can migrate your regular token to oauth token by making a _POST_ request to this endpoint https://api.robinhood.com/oauth2/migrate_token/ . Use this tokenn as _Bearer_ in authorization token and it should work.

Hey aterletskiy, I have been trying to mess with this issue for days and I can't figure it out. How did you go about changing the crypto code to accept the new oauth token?

**Comment by aterletskiy** [comment]
Not sure what you're referring to by **crypto code** but if you can't get authentication to work you can take a look at the `login` method in my fork here https://github.com/aterletskiy/robinhood-ruby/blob/master/lib/robinhood-ruby/rest/client.rb#L74 .  I haven't touched this code in a while so I'm not sure if it's in a working state at the moment or not.  That `client_id` value - I took it from the requests that RH web app was making, so it may have to change.
