### ISSUE TITLE
This version of Robinhood is no longer supported. Please update your app or use Robinhood for Web to log in to your account

### ISSUE THREAD

**Issue by codebykyle** [mstrum/robinhood-python#34]
There is an error logging in. The detail is as follows:

`This version of Robinhood is no longer supported. Please update your app or use Robinhood for 
Web to log in to your account`

I have a working patch I will post shortly as a comment here if you're also getting this error. If someone would like to submit a PR or more information on how to correctly solve this outside of my decidedly hacky patch, I'd love to know.

**Comment by codebykyle** [comment]
Inside of the RobinhoodClient.py file:

Add the `1.265.0` API version to the common headers. I also changed over the User-Agent to Chrome due to the fact there is a device ID and I am logging in from a desktop:

```
    common_headers = {
        'Accept': '*/*',
        'Accept-Encoding': 'gzip, deflate',
        'Accept-Language': 'en;q=1',
        'Content-type': 'application/x-www-form-urlencoded; charset=utf-8',
        'X-Robinhood-API-Version': '1.265.0',
        'Connection': 'keep-alive',
        'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36',
    }
```

In `set_auth_token_with_credentials`, set the following to the body:
```

    body = {
      'username': username,
      'password': password,
      'grant_type': 'password',
      'device_token': 'CopyYourDeviceTokenUUIDHere',
      'expires_in': 86400,
      'scope': 'internal',
      'client_id': self._client_id
    }
```

Copy your device UUID into the relevant body field to test.

I'm not sure where the device token UUID is being generated. I haven't read too much into it. I just logged in and copied the value from the post request that was submitted from my browser. Assuming this is as it says, and is a device token, this should perhaps be promoted to a parameter for this function.

**Comment by mstrum** [comment]
Interesting, I haven't touched robinhood for awhile, but I'll definitely take any PRs to fix this~

**Comment by codebykyle** [comment]
I haven't really looked to see what is needed to scrape or deal with device ID in an automated way. When I went to log-in on the Robinhood website, I was required to do a 2FA via email or phone. Once I completed that, this device-id was returned to me. 

I can submit a super quick PR whereby you pass the device ID as a parameter, but that is obviously a breaking change both in terms of code and workflow for users, and all the various scripts need to be updated to accommodate that.

I am just setting a `ROBINHOOD_DEVICE_ID` as an env variable, and passing that into the login script, and using that as a hotfix. More investigation though into what that field is and its source would be required, to know if its worth updating. 

This was an error I encountered, that I'm not sure is relevant to everyone.

I do not use the scripts here and rely on my own implementation using the `RobinhoodClient` class. I'm afraid I dont have a ton of time to go through the other scripts and ensure they're working correctly right this minute. If no one else submits a PR, and you feel this is a required breaking change, I can flush out my changes and submit them if you'd like.

Thanks,,
-Kyle

**Comment by klepsydra** [comment]
Great work!  @codebykyle  Yes, please submit your changes, or at least point me to your ROBINHOOD_DEVICE_ID env hotfix, that I may apply the right git pull from it.  
All I know enough to do is generate a verification code to email, using https://github.com/aamazie/Robinhood/blob/master/Robinhood/Robinhood.py , and already built an imap listener which can parse and submit that five-minute six-digit code to some other script.  However, I'd still be a long way from figuring out how to turn that into a working solution for this project _robinhood-python_.

**Comment by linuxs** [comment]
They're storing the device_id as a cookie in the browser, it doesn't seem to be exposed in the actual post request.

**Comment by rbdl1** [comment]
So, if I have an active device ID, how can I inject it into the script in order to download my portfolio?
