### ISSUE TITLE
What is the status of this script?

### ISSUE THREAD

**Issue by rbdl1** [mstrum/robinhood-python#38]
I'd like to use it to fetch my portfolio data from RH. Can this be done these days?

**Comment by rbdl1** [comment]
Seems like this patched fork might be the best hope, how does one insert one's device_id into the script to be used? @wangbin94 might know, but alas there appears no way to open an issue on his fork. :(

https://github.com/wangbin94/robinhood-python

**Comment by mstrum** [comment]
I've actually moved away from Robinhood so I'm not actively working on this repository. I'm always open to pull requests, or you can fork and work off of it.

**Comment by rbdl1** [comment]
I see, wish I knew Python.
