### ISSUE TITLE
Support Python 2

### ISSUE THREAD

**Issue by mstrum** [mstrum/robinhood-python#9]
So far I've just been deving on Python 3.  If I want to publish it, I may want to add Python 2 support.  Then again...

**Comment by dleen** [comment]
Let Python 2 die a graceful death 👎

**Comment by dude8604** [comment]
I would like Python 2 support.

**Comment by bubthegreat** [comment]
I'm with @dleen - Let python2 die - it's EOL soon.  I'd rather you waste your time on feature enhancements than on backporting support for a version of python that won't be supported in 2 years. 🗡
